# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_cov <- function(model, d, p, gpu = FALSE) {
    .Call('RcppGP_calc_cov', PACKAGE = 'RcppGP', model, d, p, gpu)
}

calc_inv_cov <- function(model, d, p, gpu = FALSE) {
    .Call('RcppGP_calc_inv_cov', PACKAGE = 'RcppGP', model, d, p, gpu)
}

calc_low_rank_cov <- function(model, d, p, rank, over_samp = 5L, qr_iter = 2L, gpu = FALSE) {
    .Call('RcppGP_calc_low_rank_cov', PACKAGE = 'RcppGP', model, d, p, rank, over_samp, qr_iter, gpu)
}

valid_cov_funcs <- function() {
    .Call('RcppGP_valid_cov_funcs', PACKAGE = 'RcppGP')
}

valid_nparams <- function(func_r) {
    .Call('RcppGP_valid_nparams', PACKAGE = 'RcppGP', func_r)
}

euclid <- function(X, Y) {
    .Call('RcppGP_euclid', PACKAGE = 'RcppGP', X, Y)
}

euclid_sym <- function(X) {
    .Call('RcppGP_euclid_sym', PACKAGE = 'RcppGP', X)
}

check_gpu_mem <- function() {
    invisible(.Call('RcppGP_check_gpu_mem', PACKAGE = 'RcppGP'))
}

init <- function(verbose = FALSE) {
    invisible(.Call('RcppGP_init', PACKAGE = 'RcppGP', verbose))
}

finalize <- function() {
    invisible(.Call('RcppGP_finalize', PACKAGE = 'RcppGP'))
}

reset <- function() {
    invisible(.Call('RcppGP_reset', PACKAGE = 'RcppGP'))
}

gpu_chol <- function(m, uplo = 'U') {
    .Call('RcppGP_gpu_chol', PACKAGE = 'RcppGP', m, uplo)
}

gpu_mat_mult <- function(A, B, opA, opB, swap) {
    .Call('RcppGP_gpu_mat_mult', PACKAGE = 'RcppGP', A, B, opA, opB, swap)
}

gpu_fill_rnorm <- function(m, mu, sigma) {
    .Call('RcppGP_gpu_fill_rnorm', PACKAGE = 'RcppGP', m, mu, sigma)
}

gpu_rand_prod <- function(m, l) {
    .Call('RcppGP_gpu_rand_prod', PACKAGE = 'RcppGP', m, l)
}

gpu_rand_proj <- function(m, rank, over_samp = 5L, qr_iter = 2L) {
    .Call('RcppGP_gpu_rand_proj', PACKAGE = 'RcppGP', m, rank, over_samp, qr_iter)
}

gpu_QR_Q <- function(m) {
    .Call('RcppGP_gpu_QR_Q', PACKAGE = 'RcppGP', m)
}

gpu_eig_sym <- function(m) {
    .Call('RcppGP_gpu_eig_sym', PACKAGE = 'RcppGP', m)
}

gpu_low_rank_sym <- function(m, rank, over_samp = 5L, qr_iter = 2L) {
    .Call('RcppGP_gpu_low_rank_sym', PACKAGE = 'RcppGP', m, rank, over_samp, qr_iter)
}

